#!/bin/bash

minikube kubectl -- scale deploy messaging-deploy --replicas 3
minikube kubectl -- get pods 
minikube kubectl -- describe deploy messaging-deploy

wrk -t12 -c400 -d30s http://127.0.0.1:8000/api

minikube kubectl -- top pods