# Generated by Django 5.2.8 on 2025-11-20 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='messages_convers_e551d4_idx',
        ),
        migrations.AlterField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(db_column='conversation_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chats.conversation'),
        ),
        migrations.RenameField(
            model_name='message',
            old_name='conversation',
            new_name='conversation_id',
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation_id', 'sent_at'], name='messages_convers_e551d4_idx'),
        ),
    ]
